Missing libm for rrdq by Dan Molik <dan@danmolik.com> 2015-07-30
Failed to compile rrdq on Gentoo with GCC-4.9.2 and GLIBC-2.20 with
error:

/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.2/../../../../x86_64-pc-linux-gnu/bin/ld:
src/rrdq.o: undefined reference to symbol 'floor@@GLIBC_2.2.5'
/lib64/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:560: recipe for target 'rrdq' failed
make: *** [rrdq] Error 1